# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField()),
                ('load', models.IntegerField(default=1)),
                ('roofArea', models.FloatField(default=120)),
            ],
        ),
    ]
